#jdbc连接信息+druid连接池
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://49.234.77.189:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
