server:
  port: 8082
  # dubbo-consumer.properties
dubbo:
  application:
    name: annotation-consumer
  #  registry:
  #    address: redis://127.0.0.1:6379
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://49.234.77.189:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver